services:
  godis:
    image: ghcr.io/Hoverhuang-er/godis:latest
    ports:
      - "6399:6399"
    volumes:
      - godis-data:/data
      - ./config/standalone.toml:/etc/godis/standalone.toml:ro
    environment:
      - CONFIG=/etc/godis/standalone.toml
    restart: unless-stopped

volumes:
  godis-data:
