apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "godis.fullname" . }}
  labels: {{ include "godis.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "godis.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "godis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "godis.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: godis
          image: "{{ .Values.image.repository }}:{{ include "godis.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.config.port }}
              protocol: TCP
            {{- if eq .Values.mode "cluster" }}
            - name: raft
              containerPort: {{ .Values.cluster.raftPort }}
              protocol: TCP
            {{- end }}
          env:
            - name: CONFIG
              value: /etc/godis/standalone.toml
          {{- with .Values.securityContext }}
          securityContext: {{ toYaml . | nindent 12 }}
          {{- end }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/godis
              readOnly: true
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "godis.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
