//go:build !ignore_autogenerated
// +build !ignore_autogenerated
package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties into another GodisCluster.
func (in *GodisCluster) DeepCopyInto(out *GodisCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of GodisCluster.
func (in *GodisCluster) DeepCopy() *GodisCluster {
	if in == nil {
		return nil
	}
	out := new(GodisCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *GodisCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another GodisClusterList.
func (in *GodisClusterList) DeepCopyInto(out *GodisClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GodisCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of GodisClusterList.
func (in *GodisClusterList) DeepCopy() *GodisClusterList {
	if in == nil {
		return nil
	}
	out := new(GodisClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *GodisClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another GodisClusterSpec.
func (in *GodisClusterSpec) DeepCopyInto(out *GodisClusterSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(GodisConfig)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		**out = **in
	}
	if in.ServiceAnnotations != nil {
		in, out := &in.ServiceAnnotations, &out.ServiceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of GodisClusterSpec.
func (in *GodisClusterSpec) DeepCopy() *GodisClusterSpec {
	if in == nil {
		return nil
	}
	out := new(GodisClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another GodisClusterStatus.
func (in *GodisClusterStatus) DeepCopyInto(out *GodisClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of GodisClusterStatus.
func (in *GodisClusterStatus) DeepCopy() *GodisClusterStatus {
	if in == nil {
		return nil
	}
	out := new(GodisClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another GodisConfig.
func (in *GodisConfig) DeepCopyInto(out *GodisConfig) {
	*out = *in
}

// DeepCopy creates a deep copy of GodisConfig.
func (in *GodisConfig) DeepCopy() *GodisConfig {
	if in == nil {
		return nil
	}
	out := new(GodisConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another StorageSpec.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}
